version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo_db        
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2024!
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/DbScripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - todo-net

  api:
    build:
      context: .
      dockerfile: ./backend/ToDo.Api/Dockerfile
      target: runtime
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=todo_db;Username=postgres;Password=Postgres2024!
    networks:
      - todo-net
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:80"
    depends_on:
      - api
    networks:
      - todo-net
volumes:
  postgres_data:

networks:
  todo-net:
    driver: bridge